version: '2.4'

services:
  api-companies:
    build:
      context: ./api-companies
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./api-companies:/app/
    environment:
      - SERVICE=api-companies
    env_file:
      - ./api-companies/.env

  api-persons:
    build:
      context: ./api-persons
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3002:3002"
    volumes:
      - ./api-persons:/app/
    environment:
      - SERVICE=api-persons
    env_file:
      - ./api-persons/.env

volumes:
  data:
