version: '3.8'

services:
  api-companies:
    build:
      context: ./api-companies
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./api-companies:/app/
    environment:
      - SERVICE=api-companies
    env_file:
      - ./api-companies/.env
    networks:
      - my-network

  api-persons:
    build:
      context: ./api-persons
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3002:3002"
    volumes:
      - ./api-persons:/app/
    environment:
      - SERVICE=api-persons
    env_file:
      - ./api-persons/.env
    networks:
      - my-network

  api-clients:
    build:
      context: ./api-clients
      args:
        - NODE_ENV=development
      target: dev
    ports:
      - "3004:3004"
    volumes:
      - ./api-clients:/app/
    environment:
      - SERVICE=api-clients
    env_file:
      - ./api-clients/.env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
