openapi: 3.0.1
info:
  title: API Companies Service
  version: 1.0.0
  description: API Companies Service endpoints
  contact:
    email: duardbr@gmail.com
    name: Carlos Eduardo
servers:
  - url: /
paths:
  /health:
    get:
      summary: Get API Health
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                api-companies: ok

  /companies:
    get:
      summary: Get fake companies
      parameters:
        - name: _quantity
          in: query
          description: The number of companies to generate
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                companies:
                  - id: 1
                    name: Example Company 1
                    email: example1@example.com
                    vat: 123456789
                    phone: +1234567890
                    country: Example Country
                    addresses:
                      - id: 1
                        street: Example Street 1
                        streetName: Example Street
                        buildingNumber: 123
                        city: Example City
                        zipcode: 12345
                        country: Example Country
                        county_code: EX
                        latitude: 12.345678
